### ISSUE TITLE
US - Mobile First

### ISSUE THREAD

**Issue by fabrikate** [ccoltrera/lender#13]
As a user I want to use this app on my smartphone first. 

This will require bootstrap - a mobile first fluid grid system.  http://getbootstrap.com/getting-started/#download

**Comment by fabrikate** [comment]
Downloaded Bootstrap library and added to our github.
Linked Bootstrap to html skeleton.

Bootstrap has predefined columns, buttons and other tags that will make our job easier. 
Ask if you have any questions!

**Comment by Sueonmaui** [comment]
Sounds wonderful Kate! Should I download it from your link to my computer?
